"""Init JobTrack CRM schemas

Revision ID: f142be63bf8b
Revises: 
Create Date: 2026-08-19 22:10:43.727903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f142be63bf8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('recruiter_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('source', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('work_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('application_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('next_followup_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_jobs_next_followup_date'), 'jobs', ['next_followup_date'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_foreign_key(None, 'jobs', 'recruiters', ['recruiter_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('groq_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('uploads_remaining', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_ctc', sa.String(), nullable=True))
    op.add_column('users', sa.Column('expected_ctc', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lwd', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notice_period', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_roles', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_locations', sa.String(), nullable=True))
    op.add_column('users', sa.Column('work_preference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_preference')
    op.drop_column('users', 'preferred_locations')
    op.drop_column('users', 'target_roles')
    op.drop_column('users', 'notice_period')
    op.drop_column('users', 'lwd')
    op.drop_column('users', 'expected_ctc')
    op.drop_column('users', 'current_ctc')
    op.drop_column('users', 'uploads_remaining')
    op.drop_column('users', 'groq_key')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_next_followup_date'), table_name='jobs')
    op.drop_column('jobs', 'notes')
    op.drop_column('jobs', 'next_followup_date')
    op.drop_column('jobs', 'application_date')
    op.drop_column('jobs', 'work_type')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'source')
    op.drop_column('jobs', 'recruiter_id')
    op.drop_column('jobs', 'company_id')
    # ### end Alembic commands ###
